INSERT INTO flight (FLIGHT_NUMBER,FLIGHT_ORIGIN,FLIGHT_DESTINATION,DEPARTURE_TIME,ARRIVAL_TIME,FLIGHT_PRICE)
VALUES ('A101','AMS','DEL',PARSEDATETIME('11:00','HH:mm'),PARSEDATETIME('17:00','HH:mm'),850); 

INSERT INTO flight (FLIGHT_NUMBER,FLIGHT_ORIGIN,FLIGHT_DESTINATION,DEPARTURE_TIME,ARRIVAL_TIME,FLIGHT_PRICE)
VALUES ('B101','AMS','BOM',PARSEDATETIME('12:00','HH:mm'),PARSEDATETIME('19:30','HH:mm'),750); 

INSERT INTO flight (FLIGHT_NUMBER,FLIGHT_ORIGIN,FLIGHT_DESTINATION,DEPARTURE_TIME,ARRIVAL_TIME,FLIGHT_PRICE)
VALUES ('C101','AMS','BOM',PARSEDATETIME('13:00','HH:mm'),PARSEDATETIME('18:30','HH:mm'),800); 

INSERT INTO flight (FLIGHT_NUMBER,FLIGHT_ORIGIN,FLIGHT_DESTINATION,DEPARTURE_TIME,ARRIVAL_TIME,FLIGHT_PRICE)
VALUES ('D101','AMS','MAA',PARSEDATETIME('09:00','HH:mm'),PARSEDATETIME('15:00','HH:mm'),600); 


INSERT INTO flight (FLIGHT_NUMBER,FLIGHT_ORIGIN,FLIGHT_DESTINATION,DEPARTURE_TIME,ARRIVAL_TIME,FLIGHT_PRICE)
VALUES ('E101','MAA','BOM',PARSEDATETIME('16:00','HH:mm'),PARSEDATETIME('17:30','HH:mm'),100); 


INSERT INTO flight (FLIGHT_NUMBER,FLIGHT_ORIGIN,FLIGHT_DESTINATION,DEPARTURE_TIME,ARRIVAL_TIME,FLIGHT_PRICE)
VALUES ('F101','BOM','DEL',PARSEDATETIME('20:30','HH:mm'),PARSEDATETIME('21:30','HH:mm'),80); 

INSERT INTO flight (FLIGHT_NUMBER,FLIGHT_ORIGIN,FLIGHT_DESTINATION,DEPARTURE_TIME,ARRIVAL_TIME,FLIGHT_PRICE)
VALUES ('G101','BOM','DEL',PARSEDATETIME('18:00','HH:mm'),PARSEDATETIME('19:30','HH:mm'),100); 



INSERT INTO flight (FLIGHT_NUMBER,FLIGHT_ORIGIN,FLIGHT_DESTINATION,DEPARTURE_TIME,ARRIVAL_TIME,FLIGHT_PRICE)
VALUES ('A201','LHR','DEL',PARSEDATETIME('11:30','HH:mm'),PARSEDATETIME('17:00','HH:mm'),600);


INSERT INTO flight (FLIGHT_NUMBER,FLIGHT_ORIGIN,FLIGHT_DESTINATION,DEPARTURE_TIME,ARRIVAL_TIME,FLIGHT_PRICE)
VALUES ('B201','LHR','BOM',PARSEDATETIME('12:35','HH:mm'),PARSEDATETIME('19:30','HH:mm'),750);


INSERT INTO flight (FLIGHT_NUMBER,FLIGHT_ORIGIN,FLIGHT_DESTINATION,DEPARTURE_TIME,ARRIVAL_TIME,FLIGHT_PRICE)
VALUES ('C201','LHR','BLR',PARSEDATETIME('13:45','HH:mm'),PARSEDATETIME('18:30','HH:mm'),800);


INSERT INTO flight (FLIGHT_NUMBER,FLIGHT_ORIGIN,FLIGHT_DESTINATION,DEPARTURE_TIME,ARRIVAL_TIME,FLIGHT_PRICE)
VALUES ('D201','LHR','MAA',PARSEDATETIME('09:00','HH:mm'),PARSEDATETIME('15:00','HH:mm'),600);


INSERT INTO flight (FLIGHT_NUMBER,FLIGHT_ORIGIN,FLIGHT_DESTINATION,DEPARTURE_TIME,ARRIVAL_TIME,FLIGHT_PRICE)
VALUES ('E201','DEL','BOM',PARSEDATETIME('18:45','HH:mm'),PARSEDATETIME('20:15','HH:mm'),100);

INSERT INTO flight (FLIGHT_NUMBER,FLIGHT_ORIGIN,FLIGHT_DESTINATION,DEPARTURE_TIME,ARRIVAL_TIME,FLIGHT_PRICE)
VALUES ('F201','BOM','DEL',PARSEDATETIME('21:15','HH:mm'),PARSEDATETIME('22:30','HH:mm'),80);

INSERT INTO flight (FLIGHT_NUMBER,FLIGHT_ORIGIN,FLIGHT_DESTINATION,DEPARTURE_TIME,ARRIVAL_TIME,FLIGHT_PRICE)
VALUES ('G201','BOM','DEL',PARSEDATETIME('20:20','HH:mm'),PARSEDATETIME('21:30','HH:mm'),100);