DROP TABLE IF EXISTS FLIGHT;
CREATE TABLE FLIGHT (  
FLIGHT_ID INT AUTO_INCREMENT  PRIMARY KEY,  
FLIGHT_NUMBER CHARACTER VARYING(255) NOT NULL,
ARRIVAL_TIME TIMESTAMP(6) NOT NULL, 
DEPARTURE_TIME TIMESTAMP(6) NOT NULL, 
FLIGHT_PRICE DOUBLE PRECISION NOT NULL,
FLIGHT_DESTINATION CHARACTER VARYING(255) ,
FLIGHT_ORIGIN CHARACTER VARYING(255)
);